repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        types: [ jupyter ]
        stages: [ commit ]
        language: python
        additional_dependencies:
          - jupyter
        entry: jupyter nbconvert --clear-output --inplace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
